#####################################################################
## CMakeLists.txt --- ci-inria.yml
## CI script for https://gitlab.inria.fr/gismo/gismo
## This file is part of the G+Smo library.
##
## Author: Angelos Mantzaflaris
##
######################################################################
stages:
  - compile
  - test
  - compile2

.linux-gcc:
  tags:
    - ci.inria.fr
    - large
  image: docker:20.10.16

.linux-intel:
  before_script:
    - source /opt/intel/oneapi/setvars.sh
  variables:
    #GIT_STRATEGY: clone
    GIT_CLEAN_FLAGS: none
  tags:
    - ubuntu-gs

.windows:
  variables:
    GIT_CLEAN_FLAGS: none
  tags:
    - windows-gs

.macos-clang:
  variables:
    GIT_CLEAN_FLAGS: none
  tags:
    - macos-gs

Superbuild-Intel-oneAPI:
  extends: .linux-intel
  stage: compile
  before_script:
    - source /opt/intel/oneapi/setvars.sh
    - export CC=icx
    - export CXX=icpx
  interruptible: true
  script:
    - ctest -S cmake/ctest_script.cmake -D CTEST_SITE="$CI_COMMIT_BRANCH-$CI_COMMIT_SHORT_SHA [inria-ci]" -D CTEST_CMAKE_GENERATOR="Unix Makefiles" -D CTEST_BUILD_JOBS=13 -D CTEST_BINARY_DIRECTORY=../build -D CTEST_CONFIGURATION_TYPE=Release -D LABELS_FOR_SUBPROJECTS="gismo;unittests;doc-snippets" -D CTEST_BUILD_NAME="$CI_JOB_NAME[$CI_EXTERNAL_PULL_REQUEST_IID]" -D GISMO_OPTIONAL="gsModule\\;gsOpennurbs\\;gsSpectra\\;gsElasticity\\;gsKLShell\\;gsStructuralAnalysis\\;gsUnstructuredSplines\\;gsPolynomial\\;gsHLBFGS\\;gsIncompressibleFlow" -D CMAKE_ARGS="-DGISMO_BUILD_UNITTESTS=ON;-DGISMO_BUILD_EXAMPLES=OFF;-DGISMO_SUBMODULES_HEAD=ON;-DGISMO_WITH_PYBIND11=ON;-DGISMO_WITH_OPENMP=ON;-DGISMO_WITH_PARDISO=ON;-DPARDISO_USE_MKL=ON-DEIGEN_USE_MKL_ALL=OFF;-DMKL_ARCH=intel64;-DMKL_INTERFACE=lp64" #-VV

doc:
  extends: .linux-intel
  stage: compile2
  needs:
    - Superbuild-Intel-oneAPI
  only:
    - stable
  interruptible: false
  script:
    - cd ../build
    - cmake --build . -j 10 --target pygismo
    - cmake --build . -j 10 --target doc
    - ctest --add-notes doc/doxygen.log -M Experimental -T Submit
    # Add Julia docs
    - rm -rf doc.zip*
    - wget https://github.com/gismo/Gismo.jl/releases/download/doc/doc.zip
    - unzip -o doc.zip -d doc/html
    # end add Julia docs
    - cd doc/html
    - rm -rf .git
    - git config --global init.defaultBranch master
    - git init
    - git config user.email "doc@gismo.ci"
    - git config user.name "doc-ci"
    - git add .
    - git commit --quiet -m "G+Smo doc"
    - git push --force --quiet https://$GITHUB@github.com/gismo/gismo.github.io.git master:master
    - echo "CDASH report with Doxygen log:\nhttps://cdash-ci.irisa.fr/index.php?project=Gismo&filtercount=2&filtercombine=and&field1=buildname&compare1=65&value1=Superbuild-Intel-oneAPI&field2=site&compare2=65&value2=$CI_COMMIT_BRANCH-$CI_COMMIT_SHORT_SHA [inria-ci]"

build-examples:
  extends: .linux-intel
  stage: compile2
  needs:
    - Superbuild-Intel-oneAPI
  only:
    - stable
  interruptible: true
  script:
    - ctest -S cmake/ctest_script.cmake -D CTEST_SITE="$CI_COMMIT_BRANCH-$CI_COMMIT_SHORT_SHA [inria-ci]" -D CTEST_CMAKE_GENERATOR="Unix Makefiles" -D CTEST_BUILD_JOBS=13 -D CTEST_BINARY_DIRECTORY=../build -D CTEST_CONFIGURATION_TYPE=Release -D LABELS_FOR_SUBPROJECTS="examples;doc-snippets" -D CTEST_BUILD_NAME="Superbuild-Intel-oneAPI[$CI_EXTERNAL_PULL_REQUEST_IID]" -D GISMO_OPTIONAL="gsModule\\;gsOpennurbs\\;gsSpectra\\;gsElasticity\\;gsKLShell\\;gsStructuralAnalysis\\;gsUnstructuredSplines\\;gsPolynomial\\;gsHLBFGS" -D CMAKE_ARGS="-DGISMO_BUILD_UNITTESTS=ON;-DGISMO_BUILD_EXAMPLES=ON;-DGISMO_SUBMODULES_HEAD=ON;-DGISMO_WITH_PYBIND11=ON;-DGISMO_WITH_OPENMP=ON" #-VV

Superbuild-VS_17_2022:
  extends: .windows
  stage: compile
  interruptible: true
  script:
    - ctest -S cmake/ctest_script.cmake -D CTEST_SITE="$CI_COMMIT_BRANCH-$CI_COMMIT_SHORT_SHA [inria-ci]" -D CTEST_CMAKE_GENERATOR="Visual Studio 17 2022" -D CTEST_BUILD_JOBS=9 -D CTEST_CONFIGURATION_TYPE=RelWithDebInfo -D CTEST_BUILD_NAME="Superbuild-MSVC[$CI_EXTERNAL_PULL_REQUEST_IID]" -D GISMO_OPTIONAL="gsModule\\;gsOpennurbs\\;gsSpectra\\;gsElasticity\\;gsKLShell\\;gsStructuralAnalysis\\;gsUnstructuredSplines\\;gsPolynomial\\;gsHLBFGS" #-VV

Superbuild-OSX-AppleClang:
  extends: .macos-clang
  stage: compile
  interruptible: true
  script:
    - ctest -S cmake/ctest_script.cmake -D CTEST_SITE="$CI_COMMIT_BRANCH-$CI_COMMIT_SHORT_SHA_[inria-ci]" -D CTEST_CMAKE_GENERATOR="Unix Makefiles" -D CTEST_BUILD_JOBS=13 -D CTEST_BUILD_NAME="$CI_JOB_NAME[$CI_EXTERNAL_PULL_REQUEST_IID]" -D GISMO_OPTIONAL="gsModule\\;gsOpennurbs\\;gsSpectra\\;gsElasticity\\;gsKLShell\\;gsStructuralAnalysis\\;gsUnstructuredSplines\\;gsPolynomial\\;gsHLBFGS" #-VV
